"""Tests for wiring feed-health alerting into the edition crons.

Requirement (2026-09-13): "check_feeds and updating the source-status/ page
should be part of the news updating crons that already exist."

The status page was already regenerated by run_edition.sh; what was missing was
*alerting*. Three properties make that wiring safe, and each is easy to get
wrong:

1. **No duplicate fetching.** The edition pipeline already fetches all 34 feeds
   and records health before dedup on every run. Re-fetching in the monitor
   would double-count every failure (driving the consecutive_failures counter
   that *gates alerting*) and burn 34 extra requests three times a day.
   ``alerts_only`` reads the persisted health instead.

2. **No alert spam.** A feed that stays broken must alert once, not on every
   subsequent run. An ``alerted_at_failures`` marker suppresses repeats until
   the streak grows or recovers.

3. **A dry run must not consume an alert.** Persisting the marker on a dry run
   would let a test silence a real production warning.

Also pinned: the single-writer rule. Both the monitor and the pipeline merge
through ``generate_news.record_feed_health()`` so their failure streaks cannot
disagree.
"""

import json
import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

sys.path.insert(0, str(PROJECT_ROOT / "tools"))

import generate_news  # noqa: E402
from check_feeds import (  # noqa: E402
    ALERT_THRESHOLD,
    check_all_feeds,
    load_health,
    save_health,
)


def make_site_root(tmp_path: Path, feeds: dict[str, str]) -> Path:
    site_root = tmp_path / "site"
    site_root.mkdir()
    (site_root / "sections.json").write_text(json.dumps({
        "source_urls": {},
        "sections": [{"title": "News", "subsections": [
            {"title": "SubA", "feeds": feeds},
        ]}],
    }), encoding="utf-8")
    return site_root


class TestAlertsOnlyDoesNotFetch(unittest.TestCase):
    """The whole point: reuse health the pipeline wrote, don't re-fetch."""

    def test_alerts_only_never_calls_check_feed(self):
        with tempfile.TemporaryDirectory() as td:
            site_root = make_site_root(Path(td), {"A": "https://a/rss"})
            save_health(site_root, {
                "A": {"url": "https://a/rss", "consecutive_failures": 0,
                      "last_success": "2026-09-13T00:00:00+00:00",
                      "last_failure": None, "last_error": None},
            })
            with patch("check_feeds.check_feed") as m:
                check_all_feeds(site_root, alerts_only=True)
            m.assert_not_called()

    def test_alerts_only_reports_healthy_from_state(self):
        with tempfile.TemporaryDirectory() as td:
            site_root = make_site_root(Path(td), {"A": "https://a/rss"})
            save_health(site_root, {
                "A": {"url": "https://a/rss", "consecutive_failures": 0,
                      "last_success": "2026-09-13T00:00:00+00:00",
                      "last_failure": None, "last_error": None},
            })
            results = check_all_feeds(site_root, alerts_only=True)
            self.assertEqual(len(results), 1)
            self.assertTrue(results[0]["ok"])

    def test_alerts_only_reports_failing_from_state(self):
        with tempfile.TemporaryDirectory() as td:
            site_root = make_site_root(Path(td), {"A": "https://a/rss"})
            save_health(site_root, {
                "A": {"url": "https://a/rss",
                      "consecutive_failures": ALERT_THRESHOLD,
                      "last_success": None, "last_failure": "2026-09-13T00:00:00+00:00",
                      "last_error": "all 1 URL(s) failed"},
            })
            results = check_all_feeds(site_root, alerts_only=True, dry_run=True)
            self.assertFalse(results[0]["ok"])
            self.assertEqual(results[0]["consecutive_failures"], ALERT_THRESHOLD)

    def test_alerts_only_is_fast_no_fetching(self):
        """34 feeds must not be requested; this runs 3x/day."""
        feeds = {f"F{i}": f"https://f{i}/rss" for i in range(34)}
        with tempfile.TemporaryDirectory() as td:
            site_root = make_site_root(Path(td), feeds)
            save_health(site_root, {
                f"F{i}": {"url": f"https://f{i}/rss", "consecutive_failures": 0,
                          "last_success": "2026-09-13T00:00:00+00:00",
                          "last_failure": None, "last_error": None}
                for i in range(34)
            })
            with patch("check_feeds.check_feed") as m:
                check_all_feeds(site_root, alerts_only=True)
            self.assertEqual(m.call_count, 0)


class TestAlertDeDuplication(unittest.TestCase):
    """A persistently broken feed must alert once, not every run."""

    def _root_with_failing(self, failures: int, marker=None) -> Path:
        td = tempfile.TemporaryDirectory()
        self.addCleanup(td.cleanup)
        site_root = make_site_root(Path(td.name), {"A": "https://a/rss"})
        entry = {"url": "https://a/rss", "consecutive_failures": failures,
                 "last_success": None, "last_failure": "2026-09-13T00:00:00+00:00",
                 "last_error": "boom"}
        if marker is not None:
            entry["alerted_at_failures"] = marker
        save_health(site_root, {"A": entry})
        return site_root

    def test_alerts_on_first_crossing(self):
        site_root = self._root_with_failing(ALERT_THRESHOLD)
        results = check_all_feeds(site_root, alerts_only=True, dry_run=True)
        self.assertTrue(results[0]["alerted"])

    def test_does_not_realert_same_streak(self):
        site_root = self._root_with_failing(ALERT_THRESHOLD,
                                            marker=ALERT_THRESHOLD)
        results = check_all_feeds(site_root, alerts_only=True, dry_run=True)
        self.assertFalse(results[0]["alerted"], "must not spam the same streak")

    def test_realerts_when_streak_grows(self):
        site_root = self._root_with_failing(ALERT_THRESHOLD + 5,
                                            marker=ALERT_THRESHOLD)
        results = check_all_feeds(site_root, alerts_only=True, dry_run=True)
        self.assertTrue(results[0]["alerted"], "a worsening streak should re-alert")

    def test_below_threshold_never_alerts(self):
        site_root = self._root_with_failing(ALERT_THRESHOLD - 1)
        results = check_all_feeds(site_root, alerts_only=True, dry_run=True)
        self.assertFalse(results[0]["alerted"])


class TestDryRunDoesNotConsumeAlert(unittest.TestCase):
    """A test run must not silence a real warning."""

    def test_dry_run_leaves_marker_unset(self):
        with tempfile.TemporaryDirectory() as td:
            site_root = make_site_root(Path(td), {"A": "https://a/rss"})
            save_health(site_root, {
                "A": {"url": "https://a/rss",
                      "consecutive_failures": ALERT_THRESHOLD,
                      "last_success": None, "last_failure": "2026-09-13T00:00:00+00:00",
                      "last_error": "boom"},
            })
            check_all_feeds(site_root, alerts_only=True, dry_run=True)
            health = load_health(site_root)
            self.assertIsNone(health["A"].get("alerted_at_failures"),
                              "a dry run must not consume the alert")

    def test_dry_run_then_real_run_still_alerts(self):
        with tempfile.TemporaryDirectory() as td:
            site_root = make_site_root(Path(td), {"A": "https://a/rss"})
            save_health(site_root, {
                "A": {"url": "https://a/rss",
                      "consecutive_failures": ALERT_THRESHOLD,
                      "last_success": None, "last_failure": "2026-09-13T00:00:00+00:00",
                      "last_error": "boom"},
            })
            check_all_feeds(site_root, alerts_only=True, dry_run=True)
            # without a webhook the alert is logged and the marker recorded
            check_all_feeds(site_root, alerts_only=True)
            health = load_health(site_root)
            self.assertEqual(health["A"].get("alerted_at_failures"), ALERT_THRESHOLD)


class TestSingleWriterRule(unittest.TestCase):
    """Both writers must merge through record_feed_health, or streaks diverge."""

    def test_monitor_uses_pipeline_record_feed_health(self):
        with tempfile.TemporaryDirectory() as td:
            site_root = make_site_root(Path(td), {"A": "https://a/rss"})
            with patch("check_feeds.check_feed", return_value=(False, "boom")), \
                 patch("check_feeds.record_feed_health") as m:
                check_all_feeds(site_root)
            m.assert_called_once()
            passed = m.call_args[0][1]
            self.assertEqual(passed[0]["name"], "A")
            self.assertFalse(passed[0]["ok"])

    def test_running_monitor_twice_does_not_double_count(self):
        """Two monitor runs = two failures, not three or four."""
        with tempfile.TemporaryDirectory() as td:
            site_root = make_site_root(Path(td), {"A": "https://a/rss"})
            with patch("check_feeds.check_feed", return_value=(False, "boom")):
                check_all_feeds(site_root)
                check_all_feeds(site_root)
            health = load_health(site_root)
            self.assertEqual(health["A"]["consecutive_failures"], 2)

    def test_recovery_resets_the_streak(self):
        with tempfile.TemporaryDirectory() as td:
            site_root = make_site_root(Path(td), {"A": "https://a/rss"})
            with patch("check_feeds.check_feed", return_value=(False, "boom")):
                check_all_feeds(site_root)
                check_all_feeds(site_root)
            with patch("check_feeds.check_feed", return_value=(True, "OK")):
                check_all_feeds(site_root)
            health = load_health(site_root)
            self.assertEqual(health["A"]["consecutive_failures"], 0)
            self.assertIsNotNone(health["A"]["last_success"])


class TestCliContract(unittest.TestCase):
    """--alerts-only is advisory and must never fail an edition run."""

    def _run(self, args: list[str], site_root: Path) -> subprocess.CompletedProcess:
        env = dict(os.environ)
        env["PYTHONPATH"] = str(PROJECT_ROOT)
        return subprocess.run(
            [sys.executable, str(PROJECT_ROOT / "tools" / "check_feeds.py"),
             str(site_root), *args],
            capture_output=True, text=True, env=env,
        )

    def test_alerts_only_exits_zero_even_with_failures(self):
        """It reads state a prior step wrote; it must not fail the edition."""
        with tempfile.TemporaryDirectory() as td:
            site_root = make_site_root(Path(td), {"A": "https://a/rss"})
            save_health(site_root, {
                "A": {"url": "https://a/rss",
                      "consecutive_failures": ALERT_THRESHOLD,
                      "last_success": None, "last_failure": "2026-09-13T00:00:00+00:00",
                      "last_error": "boom"},
            })
            proc = self._run(["--alerts-only", "--dry-run"], site_root)
            self.assertEqual(proc.returncode, 0, proc.stderr)

    def test_plain_check_keeps_its_gate_semantics(self):
        """Standalone monitor behaviour is unchanged: it IS the gate there.

        The full behaviour (exit 1 on failures) is asserted in
        tests/test_feed_health.py; here we only pin that the two modes differ,
        so a future refactor cannot collapse them into one.
        """
        src = (PROJECT_ROOT / "tools" / "check_feeds.py").read_text(encoding="utf-8")
        self.assertIn("sys.exit(0 if args.alerts_only else 1)", src)


class TestRunEditionWiring(unittest.TestCase):
    """run_edition.sh must alert and rebuild the page even when the edition
    exits non-zero -- that is exactly when it matters most."""

    @classmethod
    def setUpClass(cls):
        cls.script = (PROJECT_ROOT / "run_edition.sh").read_text(encoding="utf-8")

    def test_invokes_check_feeds_alerts_only(self):
        self.assertIn("--alerts-only", self.script)

    def test_invokes_build_source_status(self):
        self.assertIn("tools/build_source_status.py", self.script)

    def test_alert_and_status_run_before_the_exit_on_failure(self):
        """Ordering matters: a degraded run must still alert and refresh."""
        rc_capture = self.script.index("EDITION_RC=$?")
        alert = self.script.index("--alerts-only")
        status = self.script.index("tools/build_source_status.py")
        bail = self.script.index('exit "$EDITION_RC"')
        self.assertLess(rc_capture, alert, "must capture the exit code first")
        self.assertLess(alert, bail, "alerting must precede the bail-out")
        self.assertLess(status, bail, "status page must precede the bail-out")

    def test_edition_failure_still_propagates(self):
        self.assertIn('exit "$EDITION_RC"', self.script)

    def test_uses_set_plus_e_around_the_edition_call(self):
        """Otherwise set -e aborts before alerting ever runs."""
        self.assertIn("set +e", self.script)
        self.assertIn("set -e", self.script)


if __name__ == "__main__":
    unittest.main()
